import { readFileSync } from 'node:fs';
import { CATALOGO } from '../src/features/reglas/data/conjuros';
import { norm } from '../src/shared/utils/texto';
const l = JSON.parse(readFileSync('../biblioteca-mi-turno.json', 'utf8'));
const sp = [...new Set([...CATALOGO, ...Object.values<any>(l.conjuros)].map(s => s.nombre))].filter(n => n.length > 3);
const re = /(conoces|aprendes|lanza|truco|conjuro)/;
const B = String.fromCharCode(92) + 'b';
const mira = (tipo: string, n: string, nombre: string, t: string) => { const nt = norm(t); if (!re.test(nt)) return;
  const hits = sp.filter(s => new RegExp(B + norm(s).replace(/[/()]/g, '.') + B).test(nt)); if (hits.length) console.log(`${tipo} | ${n} | ${nombre} | ${hits.join(', ')}`); };
for (const d of Object.values<any>(l.dotes)) mira('dote', d.n, d.n, d.texto || '');
for (const e of Object.values<any>(l.especies)) (e.rasgos || []).forEach((r: any) => mira('especie', e.n + (r.sub ? '/' + r.sub : ''), r.nombre, r.texto || ''));
